### ISSUE TITLE
1.16.1: Logging and notifying staff of /msgs

### ISSUE THREAD

**Issue by Jeremy5762** [kangarko/ChatControl-Free#1]
Anyways, this does not work for me:
https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#chatcontrol-wont-override-w-or-other-aliases-for-private-messages

It's not allowing anyone to tab complete player names and still does not allow /msg, /r, or /tell to notify/log/deny/etc.

This is what I have in my commands.txt:
`match ^/(r\b|reply|m\b|msg|message|tell).*`
`ignore perm chatcontrol.bypass.rules`
`then notify chatcontrol.notify.rulesalert &8[&7SocialSpy&8] &7{player}: &f{message}`
`then log`

Can I please just get support.

CHC v5.8.7

**Comment by kangarko** [comment]
Hi Jeremy,

I apology you waited for two weeks. You're saying there was absolutely no-one from my team to give you support - like no messages at all or poor communication? I recently returned back to MineAcademy so until I fix this I am the one you can return to.

Back to your issue - so you are saying that after putting your rule into the plugin, private messages are not sent? Because I just tested, and I could both tab-complete these commands and the other player with an OP could see the notify:

![a](https://i.imgur.com/kun6S8N.png) 

I am happy to help, just tell me how to find the bug, what steps to do. You can also send me your full ChatControl/ folder as a ZIP so we can resolve this asap.

Matej

**Comment by kangarko** [comment]
Please also test using 5.8.8 version, the what I just released.

**Comment by Jeremy5762** [comment]
Thank you so much for replying!

Yes, before and after trying [this](https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#chatcontrol-wont-override-w-or-other-aliases-for-private-messages), private messages aren't sent. I'm almost certain it's not a permission problem because I get notifications for other rules. My guess is it has something to do with the server host I use, Minehut. Because other Minehut related commands like /hub aren't able to be logged either. I would update the plugin to the latest version to see if that fixes it, but Minehut doesn't allow manual updating, I have to wait until they update it.

How to reproduce:
`Create Minehut account -> Create server -> Wait for server to start then stop it -> Install plugins -> Start server -> Op yourself from server dashboard -> Configure ChatControl rules in file manager -> /chc reload -> Try using /msg from non opped account -> no notification or logging =/`

Some more info:
`Server is running Paper 129`
`BungeeCord version 1.16-R0.4-SNAPSHOT`
`Plugins: ChatControl, LuckPerms, MaxBansPlus, PlayerServer (Includes Geyser plugin), ProtocolSupport, Vault, WorldEdit`
Though I have tried it with just:
`ChatControl, Vault, PlayerServer` and it produced the same result. (I can't remove/disable the PlayerServer plugin, it's Minehut's built in plugin they made)

I have attached my ChatControl folder and commands.yml file below.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Free/files/5024176/ChatControl.zip)
[commands.yml.zip](https://github.com/kangarko/ChatControl-Free/files/5024188/commands.yml.zip)

**Comment by kangarko** [comment]
Strange, I remember a problem when the console filter was enabled.

Can you try disabling this please?

![a](https://i.imgur.com/XGuY7j4.png)

**Comment by Jeremy5762** [comment]
I disabled it, still not working. =/

**Comment by kangarko** [comment]
I am trying to reproduce but using these plugins I am not able to send private messages: https://i.imgur.com/ltm7SJT.png

What plugin do you use to manage private messages? If it is on Bungee, ChatControl cannot see it because it is like one level below it.

**Comment by Jeremy5762** [comment]
I believe it is on Bungee.

**Comment by Jeremy5762** [comment]
I believe it is on Bungee.

**Comment by Jeremy5762** [comment]
I believe it is on Bungee.

**Comment by Jeremy5762** [comment]
I believe it is on Bungee.

**Comment by kangarko** [comment]
Oh that's the problem!

When your private messaging system is on Bungee, we don't see it. It's like a river - we can only see what flows downstream. BungeeCord is "above" a Minecraft server so the server itself can't see what's going on there.

Having said that, I am so sorry I was now able to help you but, I can offer you a massive 65% discount on upgrading to ChatControl Pro that supports BungeeCord-compatible private messages without any hassles. If interested, just PM me on SpigotMC ;)
