### ISSUE TITLE
1.16.3: Unknown group setting when trying to set per world chat format

### ISSUE THREAD

**Issue by Fakhri1999** [kangarko/ChatControl-Free#10]
I'm using ChatController-Free 5.9.0 
I'm trying to set the per world chat format, but I get error 

`Caused by: java.lang.RuntimeException: Unknown group setting: 'Interactive_Format', use one of these: Message_Delay, Command_Delay, Join_Message, Leave_Message, Kick_Message`

I already follow the wiki. I tried both 'Chat_Format' and 'Interactive_Format', but none of them works. And from the error message, I don't see any option for the group to set the chat format

**Comment by kangarko** [comment]
This is not supported on the free version, use one of these as the message told you: Message_Delay, Command_Delay, Join_Message, Leave_Message, Kick_Message
