### ISSUE TITLE
1.16.1 Timed Broadcast newline

### ISSUE THREAD

**Issue by xSaoul** [kangarko/ChatControl-Free#11]
Im trying to make it so it says something like 
      &5&lWant to get a headstart and cool cosmetics? 
      &dDo /buy to take a look at ranks, boosts, cosmetics and more!
Where its one broadcast seperated to multiple lines, is it possible to do this?

**Comment by kangarko** [comment]
Yes, please use this syntax:

```
Message: |-
  First line
  Second line
```
