### ISSUE TITLE
Error: Handler already set on: Rule

### ISSUE THREAD

**Issue by soy-chrislo** [kangarko/ChatControl-Free#12]
The error is not very specific, although modify some files I do not know what it means by the name of the error, what do I modify?, the file that asks me to rewrite does not even exist in the logs folder.

![image](https://user-images.githubusercontent.com/69398172/95678334-a3ba6f80-0b91-11eb-9f73-747fac6a70a5.png)

**Comment by kangarko** [comment]
Use "handle as" only once per rule.
