### ISSUE TITLE
1.16.3: Console Error

### ISSUE THREAD

**Issue by Jakaboii** [kangarko/ChatControl-Free#13]
I'm running [PurPur 1.16.3](https://github.com/pl3xgaming/Purpur) and when I start my server I get this error in the console: https://hatebin.com/wozihbuzen
I don't know what other information you need, sorry

**Comment by CreepyCz** [comment]
Plugin is for version 1.2.5 - 1.16.2
Plugin need update for version 1.16.3. I have same problem

**Comment by Jakaboii** [comment]
Oh, OK
I'll wait for a 1.16.3 update then

**Comment by kangarko** [comment]
Check your sound names in your files guys. Plugin works fine on 1.16.3 but you need to fix your sound name. Find "Sound" and change the sound name to BLOCK_NOTE_BLOCK_BASS for example.

**Comment by Jakaboii** [comment]
Oh, right yeah. That fixed it, thanks
