### ISSUE TITLE
Minecraft Version 1.16.3 : How to setup range mode?

### ISSUE THREAD

**Issue by Sebaa7** [kangarko/ChatControl-Free#15]
Hello , I have problems with the ranged mode , i have activated "set true" chat formatter and range mode , and try a few times , but  i still getting a world chat in every place of the world  , range mode  doesnt work , please help me :c

**Comment by kangarko** [comment]
Give yourself negative -chatcontrol.chat.global permission

**Comment by Sebaa7** [comment]
I do it in luckperms , reboot the server and...  it doesn't work :c if anyone write in the chat , everybody receives the message

**Comment by kangarko** [comment]
Please post your settings.yml

**Comment by Sebaa7** [comment]
# -----------------------------------------------------------------------
#         Welcome to the main configuration of ChatControl
# -----------------------------------------------------------------------
# [General support and updates]
# http://www.spigotmc.org/resources/chatcontrol.271
#
# [Default configuration with comments]
# https://github.com/kangarko/ChatControl/blob/master/settings.yml
#
# [Tips]
# - Color codes are supported with the '&' character, see
#   http://minecraftwiki.net/wiki/Formatting_codes for usage
#
# - To not display a message, set it to 'none'.
#
# - Unicode /special characters/ only work when files are saved in
#   UTF-8 encoding. Tested on Notepad++, WordPad on Windows is broken.
#
# - Most of the messages (warnings, etc) are found in the localization.
#   To customize it, make a new file in "localization/messages_LOCALE.yml"
#   (Replace LOCALE with the actuall locale name, by default 'en'). It
#   will be filled with all default values and kept with sync on updates.
# -----------------------------------------------------------------------

Anti_Bot:
  # Delay between player logging in again in seconds.
  Rejoin_Delay_Seconds: 4

  # Set if the player has to move from their join location to do following.
  Block_Actions_Until_Moved:
    # To be able to chat (player will still be able to execute commands)
    Chat: true

Anti_Caps:
  Enabled: true
  Warn_Player: true

  # Ignore player names. Exclude them from caps percentage and caps in a
row check.
  # Enabling is not recommended on a bigger servers (50+ slots) due to
iterating over every player (laggy).
  Ignore_Usernames: false
  Min_Message_Length: 5
  Min_Caps_Percentage: 50
  Min_Caps_In_A_Row: 5
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL

Anti_Spam:
  Similarity_Check:
    Ignore_Special_Characters: true
    Ignore_Duplicate_Characters: false

    # If enabled, the first and second arguments in longer commands will be
ignored.
    # This makes the check less annoying in messages like /tell <player>
message
    # where it ignores /tell and <player> name.
    Ignore_First_Arguments_In_Commands: true

  Commands:
    # Delay in seconds. Set to 0 to disable.
    Delay_Between_Commands: 0

    # If a message is similar (in percents) to the previous one, block it.
    # Set to 0 or 100 to disable.
    # We keep in mind that commands like /tell includes always name, making
the check less annonying.
    Similar_Percentage_Block: 0

    # Commands ignored from the delay check.
    Whitelist_Similarity:
    - tell
    - pm
    - t
    - w
    - r

    # Commands ignored from the similarity check.
    Whitelist_Delay:
    - spawn
    - home

  Chat:
    # Delay in seconds. Set to 0 to disable.
    Delay_Between_Messages: 1

    # If a command is similar (in percents) to the previous one, block it.
    # Set to 0 or 100 to disable.
    Similar_Percentage_Block: 0

    # Should regular expressions be supported in Whitelist_Similarity and
Whitelist_Delay?
    # ! Can lead to unexpected behavior.
    Regex_In_Whitelist: false

    # Message that starts with following strings will be ignored from the
delay check.
    Whitelist_Similarity:
    - hello
    - hey

    # Message that starts with following strings will be ignored from the
similarity check.
    Whitelist_Delay:
    - yes

Chat:
  # You need Vault to enable the formatter.
  Formatter:
    Enabled: true

    # Default chat message format.
    # The prefix has to include the 'pl_' because without it the plugin's
prefix name will be given instead.
    Message_Format: '%clans_prefix%&r{pl_prefix}{player}:{pl_suffix}
{message}'

    # If Ranged_Mode is enabled, this format is used when a message is
printed to the global chat by prefixing it with '!'
    # NB: Player must also have the 'chatcontrol.chat.global' permission to
speak to the global chat.
    Global_Message_Format:
'&8[GLOBAL]&r%clans_prefix%&r{pl_prefix}{player}:{pl_suffix} {message}'

    # If Ranged_Mode is enabled, this format is used when a player with
'chatcontrol.chat.spy' permission receives ranged message
    # that he normally should't see.
    # To spy on private messages (e.g. /tell or /mail), use Essentials
/socialspy feature.
    Spy_Message_Format: '&8SPY: [{world}&8]&f
{pl_prefix}{player}:{pl_suffix} {message}'

    # If enabled and a players write a message, it will only be sent to
players
    # within distance of the player specified in Range
    Ranged_Mode: true

    # If you want the range for entire world, give everyone
chatcontrol.chat.overrideranged permission.
    Range: 50.0

  Grammar:
    # Punctualize every sentence. Ignores URLs.
    Insert_Dot:
      Enabled: true
      Min_Message_Length: 5

    # Make the first letter of a sentence big. Ignores URLs.
    Capitalize:
      Enabled: true
      Min_Message_Length: 5

Clear:
  # Broadcast that the chat was wiped?
  Broadcast: true

  # Send only one message to staff instead of a bunch of blank lines.
  Do_Not_Clear_For_Staff: true

  # Amount of blank lines that will be printed in the console when it is
cleared.
  Console_Lines_To_Clear: 300

Messages:
  # Use 'default' to not modify, 'hide' to not display or write a custom
message
  # Variables: {player} {pl_suffix} {pl_prefix} (when Vault is installed)
  # {countrycode} and {countryname} when AuthMe is installed
  Join: default
  Quit: default
  Kick: default

  # Needs AuthMe-Reloaded. Only display quit message when the player has
logged.
  # You can disable displaying join message in AuthMe itself by enabling
'delayJoinMessage' in its config
  Show_Quit_Only_When_Logged: true

  # Automatic message broadcaster.
  Timed:
    Enabled: false
    Random_Order: false

    # If random order is enabled, the messages will be put in a cache and
not repeat until the cache is empty,
    # then it will be filled again and so on.
    Random_No_Repeat: true

    # Prefix and suffix supports variables {player} (player name) and
{world} (world name)
    Prefix: '&8[&2Tip&8]&2'
    Suffix: ''
    Delay_Seconds: 180

    # Timed messages per worlds.
    # By default every world includes global messages.
    Message_List:

      # Messages displayed in all worlds.
      global:
      - Hey, {player}, did you know that this server is running ChatControl?
      - 'Visit developer website: &ahttps://goo.gl/CT3Zdl'

      # In this world will be displayed both global messages and these
specified below.
      hardcore:
      - Grief is not permitted what-so-ever and every griefer will be
banned.
      - Can you survive the night on {world} world?

      # In this world will be displayed messages included from hardcore
world.
      hardcore_nether:
      - includeFrom hardcore

      # No messages will be broadcasted in this world.
      ignored-world:
      - excludeGlobal

      # Global messages will no be displayed in this world.
      creative:
      - excludeGlobal
      - Welcome on Creative world. Enjoy your gamemode :)

Mute:
  # Broadcast that the chat was mute?
  Broadcast: true

  # Hide the following messages when the chat is muted
  Silence:
    Join_Messages: true
    Quit_Messages: true
    Kick_Messages: true
    Death_Messages: true

  Disabled_Commands_During_Mute:
  - me
  - tell
  - msg
  - r
  - w

# Needs ProtocolLib
Packets:
  # Enables all features that requires ProtocolLib
  # e.g. packet rules, tab complete
  Enabled: true

  # Prevent tab complete in certain cases where it can reveal server info.
  # For more advanced configuration use Spigot and configure the function
in spigot.yml
  Tab_Complete:
    Disable: true
    Disable_Only_In_Commands: true

    # If the written message/command contains space ' ', allow it.
    Allow_When_Message_Has_Space: true

    # Allow when the message length is above specific number.
    # Not recommended as it might still reveal your server setup.
    Allow_When_Length_Above: 0

# Custom rules are found in rules/ folder inside your plugins folder.
Rules:
  # Enabled in chat?
  Check_Chat: true

  # Enabled in commands?
  Check_Commands: true

  # Enabled on signs?
  Check_Signs: true

  # Needs ProtocolLib. If enabled, messages will be checked against
rules/packets.txt
  # which supports replacing even bukkit / plugin messages.
  Check_Packets: true

  Packets:

    # Since Minecraft 1.7x, every message is a chat component. Unpacking it
will bring better/more expected results.
    # Disable if experiencing issues with chat formatting plugins. Messages
with hover/click effects won't be checked.
    Deserialize_Json: true

Console:
  Filter:
    # Filter console messages specified below?
    Enabled: true

    # Remove certain messages from the server console.
    # Does not need to be whole message, just a part of the message you
want to block.
    Filter_Console_Messages:
    - Reached end of stream for
    - Connection reset
    - lost connection

Signs:
  Duplication:
    # Player will be unable to place two signs with the same text.
    Deny_Signs_With_Same_Text: false
    Alert_Staff: true

    # Block the sign (cancel event) when a custom rule matches the text on
it.
    # NOT related to duplication check but to the custom rules.
    Block_When_Violates_A_Rule: true

    # Drop sign as an item?
    Drop_Sign: true

# Plays a sound to a player that is mentioned.
Sound_Notify:
  Enabled: true

  # Play a sound to player only when their are afk? Checked from Essentials
plugin.
  Notify_Only_When_Afk: true

  # Play a sound to player only when someone writes following characters
before
  # their name: Set to none to play a sound when the players name is
mentioned in the chat.
  Notify_Only_If_Prefixed_With: '@'

  # Format: bukkit_sound_name, volume (float), pitch (float)
  # NB! In Minecraft 1.9, the sound names has changed! If you are using
1.8.x or older, the default sound name is 'CHICKEN_EGG_POP'
  # Sounds for 1.9+:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # Sounds for <=1.8:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Sound.java?until=be55b4f5b8274c1124fe957e6a3259789f6e9747
  Sound: ENTITY_CHICKEN_EGG, 1F, 1.5F
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r

# Overrides some settings above.
# There are currently only two settings.
Groups:
  Enabled: false

  # If you add a player/group permission (e.g via PermissionsEx: /pex user
<nick> add <perm>)
  # Then you will not need to reload ChatControl with /chc reload
  # Always checking has impact on performance and it is recommended to have
it disabled.
  Always_Check_Updates: false

  Group_List:

    # Example usage. Give the player chatcontrol.group.trusted to make it
working.
    # As you can see, if you do not specify the value, the default will be
used.
    trusted:
      Message_Delay: 0

    guest:
      Message_Delay: 4
      Command_Delay: 6

    vip:
      # Notice if you are an OP you need to negate those permissions
      # otherwise it will be applied on you, too!
      Join_Message: "&6[VIP] &e{player} has joined the game"
      Leave_Message: "&6[VIP] &e{player} has left the game"
      Kick_Message: none

Updater:
  Enabled: true
  Notify: true
  Download: true

  # Disable important announcements after the plugin has been loaded
  Check_Notes: true

Writer:
  # Save chat to file?
  Write_Chat_Communication: true
  Strip_Colors: true

  # Messages of following players will not get writed.
  Ignore_Players:
  - ignoredAdmin

  # Commands that will be saved along with chat messages.
  Write_Commands:
  - tell

# Advanced: Affects the order in which we format and check the chat. No
need to touch.
# Read https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
for more information.
#
# Plugins which may require changing priority of Formatter: FactionsChat,
BanManager and WorldGuard.
# You need to find the correct combination for your server yourself.
Restart after each change.
Listener_Priority:

  # Used for chat formatting. Should have the last say, meaning highest
priority.
  Formatter: HIGHEST

  # Used for checking a message against duplication, time or rules.
  Checker: NORMAL

# Minimum amount of players online for rules and anti-spam.
Minimum_Players_To_Enable_Checks: 0

# How much time a rule has to process a message? Used to prevent server
freezing with malformed rules.
Regex_Timeout_Milis: 100

# To customize a locale, make file in localization/messages_LOCALENAME.yml
# It will be filled with all the values.
# Current available locales: en (English), de (German), sk (Slovak), cz
(Czech), fr (French), nl (Dutch), se (Swedish), es (Spanish),
# vi (Vietnamese), ro (Romanian), pl (Polish) and cn (Chinese)
Locale: en

# Time of some plugin's operations is measured.
# Print a message in the console if they take longer than specified
millisecond time.
# Set to 0 to disable.
Log_Lag_Over_Milis: 100

# If a message was caught by a rule print info to the console.
# It is possible to hide individual packet rules from appearing
# with "dont verbose" operators. This currently works only on packet rules.
Verbose_Rules: true

# Removes certain messages from startup (reduces spam in the console)
# If you are having any issues, disable this and enable Verbose and Debug.
Silent_Startup: true

# Plugin saves some player data, such as their last message or command +
date of writing them, for antispam to use.
# You can decide if these data should be reset when the player quits.
Recommended in lobby (when on bungee), but not elsewhere.
Reset_Cache_On_Quit: false

# Set to true if the \n operator does not work for you.
# Before that, please ensure you've saved the file in an encoding that
supports new line operator.
Enforce_New_Line: false

# Search for players geographical information for {countryname} and
{countrycode} variables?
# Disable to improve performance a tiny bit.
Lookup_Geo_Data: true

# Enable if you are having issues, will tell you detailed info in the
console.
Debug: false

# Do not change this value, otherwise it will corrupt your plugin
installation!
Version: 4

**Comment by kangarko** [comment]
Thank you, we'll attempt to fix this in ChatControl 10 which is coming very soon. You can join our testing already today at mineacademy.org/chatcontrol
