### ISSUE TITLE
Paper 1.16.4 Removing the . at the end of the player message

### ISSUE THREAD

**Issue by mrlife000** [kangarko/ChatControl-Free#18]
Hello, im running a bungeecord network 1.16.4 version and using chatcontrol no all of them, would like to know where in the config is the point of the message, like all players write a message and everytime appears . at the end, i would like to get rid off the. if you could explain me how to fix it, i would appreciate it.

**Comment by kangarko** [comment]
Hi,

Sure, set Chat.Grammar.Insert_Dot.Enabled to false in settings :)
