### ISSUE TITLE
command blacklist support

### ISSUE THREAD

**Issue by phemmer** [kangarko/ChatControl-Free#2]
Currently the command handling facilities operate on all commands except for ones specified in the `Whitelist_Delay` and `Whitelist_Similarity` options. This is a request to instead provide a blacklist scheme.

The ultimate goal is for the ChatControl plugin to handle chat, not arbitrary commands. This means things like `/msg`. However ChatControl currently handles all commands, and whitelisting all but `/msg`, `/tell`, etc, is not practical as there are hundreds of commands on a minecraft server.

1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)  
It would allow others to use the plugin to moderate chat without affecting non-chat related commands, and without the significant (impossible?) burden of whitelisting everything.

2) What would happen if we won't implement this feature? How's your server being affected?  
Example 1. User tries any command twice in a row (could be seconds or hours apart), and receives an error. These are commands like `/shop`, `/votegui`, `/tps`, `/rules`, `/claims`, `/map`, etc. As there are way too many commands to keep track of that users may use, the feature has to be disabled (`Similar_percentage_block: 0`).
Example 2. User tries to use a command which is actually a composite command (the MyCommand plugin which can be used to alias one command in place of several consecutive commands), and receives an error about executing multiple commands too fast. Thus the feature has to be disabled (`Delay_Between_Commands: 0`).

3) If suggesting something new - Can the old system be modified/improved instead?

**Comment by kangarko** [comment]
Thank you, will consider in the 9.x.x branch!

**Comment by kangarko** [comment]
Pulled into roadmap https://mm.tt/1589858477?t=3V2HKfCGzw
