### ISSUE TITLE
Messages cannot be sent

### ISSUE THREAD

**Issue by s7an1slaw** [kangarko/ChatControl-Free#23]
Hello, today I fixed a plugin in my server and without wanting I wrote /reload confirm after which the chat control plugin did not work, all of them were told to wait 1.2 seconds and try again. Then I restarted the server hoping it would work, but it didn't work. I stopped the Spam option from config, and it told them that they could not send this message, I restarted the server once again, backed up the plugin and everything seemed normal until a player wrote an insult from rules.txt by censoring it and it happened again. Do you have any idea how I can fix it?

**Comment by kangarko** [comment]
Are you getting any errors? If the plugin does not start/reload, please post me the console output when you start/reload it.

**Comment by s7an1slaw** [comment]
I fixed it, just deleted the whole plugin and set it up again
