### ISSUE TITLE
Chat format permissions not working

### ISSUE THREAD

**Issue by Fituu** [kangarko/ChatControl-Free#25]
One of the VIP's perks on my server is chat color, but it seems like default users can use the formatting in the chat as well, no matter which permissions do i set to true/false
I've tried with chatcontrol.chat.format.* and chatcontrol.chat.format and all the variants but those seem to have 0 effect on the actual permission to type with format in the chat.
How do i fix that?

**Comment by kangarko** [comment]
Hey, in ChatControl Free there's only chatcontrol.chat.format.color permission for all colors. I recommend you upgrade to Pro, it's free now.
