### ISSUE TITLE
1.16.4: PlaceHolderAPI not working

### ISSUE THREAD

**Issue by BlueTree242** [kangarko/ChatControl-Free#26]
Hello, I am trying to add placeholderAPI to my chat message.. it doesn't work

Config:
https://prnt.sc/wffcn4

Output:
https://prnt.sc/wffbuk

**Comment by kangarko** [comment]
Use {} instead of %%

**Comment by BlueTree242** [comment]
![image](https://user-images.githubusercontent.com/69328929/103763315-4fa11900-5022-11eb-9dca-9ff904bf2f3b.png)

**Comment by kangarko** [comment]
Check if your PAPI dependency is up to date, it may as well be that DiscordSRV only replaces this when you don't use our chat formatting, sorry about that.

**Comment by BlueTree242** [comment]
First, This is not DiscordSRV, This is DiscordSRVUtils addon, and its made by me so if u want to tell me to change something lol. it works on other plugins, `PlaceholderAPI.setPlaceholders(player, "chat format")`

**Comment by kangarko** [comment]
Awesome, unfortunately we no longer make feature changes to ChatControl Free. You can try changing your priority of AsyncPlayerChatEvent from LOWEST up to MONITOR to see if any of those help.

**Comment by BlueTree242** [comment]
Is this an option in config or i have to edit source code?

**Comment by kangarko** [comment]
settings.yml —> Listener_Priority.Formatter
