### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by GamerRealm** [kangarko/ChatControl-Free#28]
Hello could u tell me what is the permission for bypassing chat cooldown? Also how do I disable the ANNOYING same or similar command thing because it annoys my players alot.

**Comment by ItzRonaldMLG** [comment]
here is a list of permissions: https://github.com/kangarko/ChatControl-Pro/wiki/Permissions
Bypassing chat cooldown: chatcontrol.bypass.time.chat
To disable command check: chatcontrol.bypass.dupe.commands
