### ISSUE TITLE
1.16.4: Error, plugin disabled

### ISSUE THREAD

**Issue by ItzRonaldMLG** [kangarko/ChatControl-Free#29]
Server version: 1.16.4
Plugin version: 5.9.1
I got this error and i dont know what it could mean: https://pastebin.com/vLBT3UBT
I hope you can help me, because it causes the plugin to be disabled. 

I Love this plugin!
I hope you can help.

**Comment by kangarko** [comment]
There's another error somewhere else. Post me the full startup log when the server starts.

**Comment by ItzRonaldMLG** [comment]
This is all i got in the log file that has anything to do with chatcontrol: https://pastebin.com/ezCiikdu

**Comment by kangarko** [comment]
Your Message_List in settings.yml is malformed, reset it, read the docs, remove or play with "includeFrom", somethings wrong there
