### ISSUE TITLE
Whitelisting domains in rules.txt not working.

### ISSUE THREAD

**Issue by tdubz1** [kangarko/ChatControl-Free#3]
Hey there,

I am trying to whitelist a few domains in rules.txt however it is just not working. Neither are the default ones. If I type imgur.com as a non-OP user it comes out in chat as imgur com which is very annoying.

Also, how do I make it so that they are domains and websites are blocked like IP addresses because you can still tell what the IP is with the dot missing.

Kind regards,

tdubz1

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#ad-filter-doesnt-work-all-dots-are-removed-example-wwwgooglecom-becomes-www-google-com
