### ISSUE TITLE
1.16.4 - How can I disable the message "please do not swear, otherwise an action will be taken!"

### ISSUE THREAD

**Issue by BigBlueDJ** [kangarko/ChatControl-Free#30]
Quick question,

I would like to disable the message that comes when people swear, how can I do this?

The message is "please do not swear, otherwise an action will be taken!"

Stay Safe!

**Comment by kangarko** [comment]
Hey! 

You can do so in rules/groups.rs file or settings.yml in Warning_Points if you use this :)
