### ISSUE TITLE
Minecraft 1.16.4: how to enable dots at end of the message?

### ISSUE THREAD

**Issue by duckiesek** [kangarko/ChatControl-Free#31]
Hello, please how can i set up the dots at the end of the message? I set min_message_length: 1 and still it won't write dots.. Thanks for help.

**Comment by duckiesek** [comment]
+ big letter at the start of the message.

**Comment by duckiesek** [comment]
I think, it is working, but i have plugin discord SVR and the Dots and Big Letter at the start of the message, are working only on discordSVR not on my minecraft server.. any sollution?

**Comment by duckiesek** [comment]
maybe it'S not bcs of DiscordSVR just tipping. I'm using free version of plugin. But still, i don't get it why it's not working.

**Comment by kangarko** [comment]
Sorry this is not working on DiscordSRV.
