### ISSUE TITLE
1.16.4: Doesn't get any dots or big letter at the start of the message

### ISSUE THREAD

**Issue by duckiesek** [kangarko/ChatControl-Free#32]
Hello, The Grammar Section isn't working well. I've setted the dots and big letter to enabled mode, and still it won't write the dots and big letter at the start of the message. Even if i do it like this:   

    # Punctualize every sentence. Ignores URLs.
    Insert_Dot:
      Enabled: true
      Min_Message_Length: 1

    # Make the first letter of a sentence big. Ignores URLs.
    Capitalize:
      Enabled: true
      Min_Message_Length: 1

**Comment by kangarko** [comment]
Give yourself negative chatcontrol.bypass.punctuate and chatcontrol.bypass.capitalize permissions.

**Comment by duckiesek** [comment]
Still it doesn't work, i have putted it as you said, and it still doesn't work. 
![image](https://user-images.githubusercontent.com/69262769/107968197-5706fb00-6fae-11eb-805f-aec9195bab4f.png)

![image](https://user-images.githubusercontent.com/69262769/107968229-60906300-6fae-11eb-9ebb-7a6fa17764c3.png)

It shows on discordSRV but not in ingame.. 

![image](https://user-images.githubusercontent.com/69262769/107968288-700fac00-6fae-11eb-8e74-75ca9b6b2b18.png)

**Comment by kangarko** [comment]
It works for me just fine using Formatter from ChatControl:

![a](https://i.imgur.com/NvPQjmk.png)

If it is not a permissions problem, then unfortunately some of your other chat-related plugins is interfering. You can read the Wiki on Listener Priorities and change the priority of the Checker in Listener_Priority.Checker in settings.yml according to that article.

**Comment by duckiesek** [comment]
I don't know what to do with listener_priority.. If the checker and formatter is on normal, then i should set it to what, to make it works?

Nevím co přesně dělat s Listener_Priority.. Když mám nastavený Formatter a Checker na normal, tak na co to musím nastavit, aby to fungovalo, a doplňovalo to ty tečky a velké písmena na začátek a konec věty?

**Comment by duckiesek** [comment]
+ to mi to smazalo prefixy z pluginu PlayerRanks, takže asi nic..

**Comment by duckiesek** [comment]
Leda nějak propojit tvůj plugin, s PlayerRanks A DiscordSRV.. pokud možno, jinak to bohužel asi nepůjde.

**Comment by kangarko** [comment]
Precitaj si ten wiki clanok, skus sa s tym pohrat a nastavit to na HIGHEST, MONITOR etc etc. Skus ci jedna z danych hodnot nepomoze. Ked nie, je mi luto, pretoze iny plugin name berie moznost upravit chat a pridat bodku.
