### ISSUE TITLE
Question: Async broadcast?

### ISSUE THREAD

**Issue by Onyxtite** [kangarko/ChatControl-Free#331]
Hey there, thanks for making the plugin, just one question, after reading the plugin description it wasn't clear to me, Does the plugin broadcast asyncronically like broadcastsXS? 

Cause i've been using both but the functions seem to overlap so I just wanted to move on to only using chatcontrol, but didnt want to negatively impact server performance from doing so.
Sorry for comparing, i know its a bit rude, i just thought it made my point a bit clearer.

Thanks for the info and for your great plugin :)

**Comment by kangarko** [comment]
Hi,

ChatControl free sends messages on the main thread, thus it is synchronized.

matej
