### ISSUE TITLE
Console Error for 1.13.2

### ISSUE THREAD

**Issue by pinkpig3777** [kangarko/ChatControl-Free#333]
I'm trying to run the plugin on a test server of paper 1.13.2. It gives this console error:
https://pastebin.com/PEX12euj

I'm using: ChatControl v5.8.1

**Comment by pinkpig3777** [comment]
Nevermind, figured out I can't use my premium setup on the free version.

**Comment by kangarko** [comment]
That's right. To clarify, you _can_ upgrade from free to pro but not backwards, that won't work.
