### ISSUE TITLE
Global Chat Cooldown

### ISSUE THREAD

**Issue by M0dii** [kangarko/ChatControl-Free#334]
**Improvement/Feature-Request.**

Add cooldown for '!' (global chat). Because now players are just abusing our flood/spam rule on the server. Cooldown would be great. And it's hard to do with other plugins since it's not a global chat _command._

**Comment by kangarko** [comment]
Hi,

we have a delay named Delay_Between_Messages and Delay_Between_Commands, have you tried those? Use CTRL+F to find them in settings.yml

**Comment by M0dii** [comment]
Sorry for rebumping. But doesn't this work with all commands and messages globally?
I mean for every command and every message even if it's not in '!' (global) chat?

**Comment by kangarko** [comment]
It should work for every command and every message as long as they are handled by ChatControl, otherwise we loose control.

**Comment by M0dii** [comment]
So how come I add like 30 second cooldown to the ' ! ' (global chat)?

I don't want people waiting 30 seconds on every message or command.

**Comment by kangarko** [comment]
Oh sorry, individual cooldowns are not currently possible, you'd have to look out for an alternative plugin for that
