### ISSUE TITLE
ChatControl Error Launching

### ISSUE THREAD

**Issue by BraydenSlayer** [kangarko/ChatControl-Free#336]
02.06 20:12:40 [Server] WARN java.lang.reflect.InvocationTargetException
02.06 20:12:40 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02.06 20:12:40 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02.06 20:12:40 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.06 20:12:40 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
02.06 20:12:40 [Server] WARN at org.mineacademy.chatcontrol.final. .Lpt3.transient(SourceFile:83)
02.06 20:12:40 [Server] WARN at org.mineacademy.chatcontrol.final. .Lpt3.protected(SourceFile:61)
02.06 20:12:40 [Server] WARN at org.mineacademy.chatcontrol.final. .Lpt3.protected(SourceFile:114)
02.06 20:12:40 [Server] WARN at org.mineacademy.chatcontrol.final. .nul.transient(SourceFile:23)
02.06 20:12:40 [Server] WARN at org.mineacademy.chatcontrol.final. .Lpt3.protected(SourceFile:53)
02.06 20:12:40 [Server] WARN at org.mineacademy.chatcontrol.ChatControl.onEnable(SourceFile:87)
02.06 20:12:40 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
02.06 20:12:40 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
02.06 20:12:40 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
02.06 20:12:40 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
02.06 20:12:40 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
02.06 20:12:40 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
02.06 20:12:40 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
02.06 20:12:40 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
02.06 20:12:40 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)

**Comment by kangarko** [comment]
This issues channel is for ChatControl free

**Comment by kangarko** [comment]
Post on the right channel and also make sure you have the latest version
