### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by DimitarBogdanov** [kangarko/ChatControl-Free#338]
The plugin doesn't work on the 1.14 version.
/pl:
![image](https://user-images.githubusercontent.com/27803292/59157555-6c2b4700-8ab5-11e9-96a9-3e6605afe6ed.png)
/chatcontrol
![image](https://user-images.githubusercontent.com/27803292/59157558-73525500-8ab5-11e9-84d6-d3330a830b97.png)

Some stuff works: /cc global
![image](https://user-images.githubusercontent.com/27803292/59157566-836a3480-8ab5-11e9-92db-6761b38e87b2.png)

And, of course, prefixes function, including /global:
![image](https://user-images.githubusercontent.com/27803292/59157569-a1d03000-8ab5-11e9-94eb-d8959fa37920.png)

But that's about it.
The plugin _does **not_** function on 1.14.
I use the same version (5.8.1) on 1.8 and it works great.

The server I am testing this on:
![image](https://user-images.githubusercontent.com/27803292/59157586-d5ab5580-8ab5-11e9-877c-11abe6873d2d.png)

**Comment by DimitarBogdanov** [comment]
![image](https://user-images.githubusercontent.com/27803292/59157602-202cd200-8ab6-11e9-9cf7-74213e4b03c5.png)

Forgot.

**Comment by DimitarBogdanov** [comment]
Funnily enough, in the console (image above) it says " - plugin is disabled", but, as I said, /cc works!

**Comment by kangarko** [comment]
Please post me your entire startup log and the full error log (the one you posted above is incomplete) - upload them to pastebin.com please.

**Comment by DimitarBogdanov** [comment]
For some reason (no /reloads), the plugin works now.
Sorry for the trouble!

**Comment by kangarko** [comment]
No problem! I am still curious about the logs, if you have them just comment below.
