### ISSUE TITLE
Clearchat issues

### ISSUE THREAD

**Issue by Conssole** [kangarko/ChatControl-Free#339]
Ops and certain staff get their chat cleared, is there anyway I can specifically list the groups

**Comment by kangarko** [comment]
Make sure you have **Do_Not_Clear_For_Staff** option on true in **settings.yml** and your staff has the **chatcontrol.bypass.clear** permission.

**Comment by Conssole** [comment]
Yes It is on with the perms, it even clears for op players with the
permission to make sure

**Comment by kangarko** [comment]
Sorry I cannot reproduce, can you test the version below?
[ChatControl-Free-5.8.2.zip](https://github.com/kangarko/ChatControl-Free/files/3315101/ChatControl-Free-5.8.2.zip)


![a](https://i.imgur.com/2swjoLq.png)
