### ISSUE TITLE
Support for EssentialsX /ignore command

### ISSUE THREAD

**Issue by slvlr** [kangarko/ChatControl-Free#34]
Almost every server uses Essentials. Currently if you /ignore <Target>, the target will no longer be able to send you messages. This is all good, except if you have Sound_Notify: Enabled: true and enabled in message commands, You will still hear the sound when an ignored player messages you, but not see the message.

Outcome:
Target will no longer hear the sound when an ignored person executors a command in notify sound list

**Comment by kangarko** [comment]
ChatControl free does no longer come with feature updates, sorry this will not be implemented

**Comment by slvlr** [comment]
This is more of a bug fix, rather than a feature?
If the message is cancelled, the sound should not occur? @kangarko

**Comment by kangarko** [comment]
The "fix" that came in Pro and Red was rather complex. In Free, the entire feature only takes a few lines of code, again, we do not integrate into a third party ignore system. Besides the plugin is open source, anyone can fork this and extend it: https://github.com/kangarko/ChatControl-Free/blob/master/src/main/java/org/mineacademy/chatcontrol/listener/ChatListener.java#L155

By the way ChatControl Pro is free of charge as of right now.
