### ISSUE TITLE
not full discord support

### ISSUE THREAD

**Issue by EOT3000** [kangarko/ChatControl-Free#340]
Let's say I want to block "hello", it works fine in-game. I say hello, and whatever I want happens. It gets blocked, I may get muted, I don't know. If I have discordSRV, it also works. I go in discord, and I see *****, instead of "hello". But, if I am angry that I couldn't say "hello" in-game, I get discord, join the discord server, and say "hello". It shows in-game completely uncensored, which is really a pain. Please, kangarko, fix this.

**Comment by EOT3000** [comment]
.

**Comment by kangarko** [comment]
ChatControl Free does not have DiscordSRV support. ChatControl Pro has one directional discord support as it is currently not possible to check the message when the player is not in the game.

**Comment by EOT3000** [comment]
really?
