### ISSUE TITLE
'IS API found: true'

### ISSUE THREAD

**Issue by MeesterMaarten** [kangarko/ChatControl-Free#341]
Hello ChatControl

I'm receiving the 'Startup [19:32:15 INFO]: IS API found: true' lines in console each time a players talks. Is it possible that this is caused by ChatControl? 

I'm running the latest 5.8.2 version on MC-1.14.2.

Thanks in advance!

Maarten.

![afbeelding](https://user-images.githubusercontent.com/46909512/59941556-c0430d80-945d-11e9-8211-149e25e27878.png)

**Comment by kangarko** [comment]
Thanks, will be fixed.
