### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by JeffRabbitYT** [kangarko/ChatControl-Free#344]
ight so this isn't really an issue, I just want to know if I can make it so I don't see the uncensored word
![image](https://user-images.githubusercontent.com/52520477/61103603-48527c80-a438-11e9-9853-0ba2e2c3e715.png)
Like that, I dont want to see that "Swear/ID unset" stuff
THANK YOU!

**Comment by kangarko** [comment]
For ChatControl free, you can edit or remove the following line in your handlers.yml file:

![a](https://i.imgur.com/BpGFVhG.png)
