### ISSUE TITLE
Console warnings

### ISSUE THREAD

**Issue by Quttar** [kangarko/ChatControl-Free#349]
When I install the plugin, there are no errors in the console. But if a player enters the server, and after that I reboot the server, warnings are displayed in the console
I am using minecraft version 1.13.2

**config.yml** https://pastebin.com/igmYtLtA
**Console warnings** https://pastebin.com/mxBQ10x6

**Comment by kangarko** [comment]
Hey,

some of the file in your ChatControl/ folder has wrong encoding. Please review the following article, open every file and save it in the proper unicode encoding:

https://github.com/kangarko/chatcontrol-pro/wiki/Use-Right-Encoding
