### ISSUE TITLE
1.16.5: Remove links/advertisements

### ISSUE THREAD

**Issue by StormyGalaxy** [kangarko/ChatControl-Free#35]
I wanted to know how I could remove a link in chat completely, as all it does is just add spaces to it, any ideas?

**Comment by StormyGalaxy** [comment]
Now that I gave them the essentials.chat.url, they can type in the full link without consequences. How do I make it to where it removes the link completely?

**Comment by kangarko** [comment]
In handlers replace Block_Message with `Replace_Word: ""` https://github.com/kangarko/ChatControl-Free/blob/master/src/main/resources/handlers.yml#L91
