### ISSUE TITLE
How i can number limit in the chat?

### ISSUE THREAD

**Issue by xcvvfsdfs** [kangarko/ChatControl-Free#351]
How i can number limit in the chat? For example when i write 234356. I gave out maxnumber its 5?

**Comment by kangarko** [comment]
I am sorry, I don't understand your question.

**Comment by xcvvfsdfs** [comment]
For example when i write 233232324. Me write number of numbers allowed 5?( limited number)

**Comment by xcvvfsdfs** [comment]
Add. thats i can limited if players write 435345345345435343434141123123123123 max limit of numbers: 5. Thats players dont can write a lot of numbers. Please help

**Comment by ArtelGG** [comment]
I personally use this rule in my `chat.txt`:
```
# Blocks excessive characters.
match (.)(?=([a-z])\1{3})
then replace
```
This will allow users to still send absurd amounts of money in commands like `/pay 100000000000`, but blocking it from cluttering global chat.

**Comment by kangarko** [comment]
Thanks Artel!

Closing.
