### ISSUE TITLE
How to change the messege for CAPS

### ISSUE THREAD

**Issue by Gymblonski** [kangarko/ChatControl-Free#357]
how to change the messege when you spam and with caps on i cant find it

**Comment by Gymblonski** [comment]
How to edit messages 'You have to wait X seconds before another message' or 'Please do not post the same or similar messages' or announcement format:
Create a folder localization in your ChatControl/ folder. Restart the server. A new file with be created there with the default values. You can change the messages in that file.
 I did this and it doesnt work

**Comment by Gymblonski** [comment]
nothing comes in the localization folder after restart

**Comment by kangarko** [comment]
I have replied to you via PM, please do not spam our support channels, only select one.
