### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Strummm** [kangarko/ChatControl-Free#359]
Hello, i'm getting this error in console when a player swears through a command. (Note it does actually censor the message which is good, just want to remove the console spam). Using ChatControl version 5.8.4 on Spigot 1.8.8 using Java 11. Error:

https://hasteb.in/uzizubah.cs

Thanks for your time.

**Comment by kangarko** [comment]
Seems like you have a regex syntax error in

^/(?|bukkit:?|help|bukkit:help)

try placing \ before the / or removing the first character. Also place \ before colons (:)
