### ISSUE TITLE
Chat Control to intercept plugin messages

### ISSUE THREAD

**Issue by Apexcode1990** [kangarko/ChatControl-Free#360]
Can I use Chat Control to intercept and edit messages sent to chat via other plugins?

**Comment by kangarko** [comment]
Hey,

ChatControl free supports it but without color support so most messages wont work.

ChatControl pro has full support including filtering messages with colors.

**Comment by Apexcode1990** [comment]
Thank you Kangarko, I will buy the premium plugin, I noticed something on the premium plugin page saying that Chat control can only be used as 1 instance if purchased? does that mean that I cannot drop the premium jar into each plugin folder of my network?

**Comment by kangarko** [comment]
You can use it on your test server + as many servers on your BungeeCord as you want.
