### ISSUE TITLE
Feature Request: Markdown formatting.

### ISSUE THREAD

**Issue by SpyceTewan** [kangarko/ChatControl-Free#362]
Hi I'm a fan of this plugin. Having one plugin that handles my entire chat is very handy to have.
I've been using a plugin that allows for some markdown formatting _like italic_, **bold** and __underlined__ text, and even combinations of all of them!

Here is the plugin I used: https://github.com/Phoenix616/MineDown

This plugin even includes its own api, so implementing this into this plugin will be really easy as you don't have to program any of the parsing logic.

**Comment by kangarko** [comment]
Thank you, very interesting however we are not taking in new features for ChatControl free nor pro right now sorry
