### ISSUE TITLE
Chat color/format permission

### ISSUE THREAD

**Issue by AlwaysAllstar25** [kangarko/ChatControl-Free#364]
I have multiple groups and most of them don't have any of the permissions: chatcontrol.chat.format.color, chatcontrol.chat.format.bold, or any permission to allow them to talk in chat with anything special. However, when I'm in a group without the permission I still can. What's the issue? (I'm not opped when testing)

Here's an example of a group I have that I can still use chat formatting with:

`name: default
permissions:
- banknote.allow
- banknote.allow.all
- cashcontrol.playerkill 
- crackshot.use.all
- chatcontrol.bypass.capitalize
- chatcontrol.bypass.caps
- chatcontrol.bypass.punctuate
- chatcontrol.bypass.replace
- chatcontrol.bypass.swear
- crackshot.buy.all
- essentials.balance
- essentials.balance.others
- essentials.balancetop
- essentials.ignore
- essentials.mail
- essentials.mail.send
- essentials.msg
- essentials.pay
- essentials.seen
- essentials.signs.use.buy
- essentials.signs.use.sell
- essentials.signs.use.warp
- essentials.spawn
- essentials.kits.thug
- phatloots.loot.EpicLoot
- essentials.motd
- essentials.list
- TradeSystem.Trade
- areashop.limits.default
- areashop.sellown
- areashop.me
- areashop.addfriend
- areashop.delfriend
- essentials.kit
- SignSlots.use.10
- SignSlots.use.25
- SignSlots.use.50
- SignSlots.use.100
- group.nondonor`

**Comment by kangarko** [comment]
Just to confirm you're on ChatControl free?

Please ZIP me your ChatControl/ folder so I can test it out.

**Comment by AlwaysAllstar25** [comment]
> Just to confirm you're on ChatControl free?
> 
> Please ZIP me your ChatControl/ folder so I can test it out.

Yes, I am using ChatControl free. Everything is working perfectly apart from anyone being able to talk in color, bolt, etc. regardless of permission. Here's what I have: 

[ChatControlZip.zip](https://github.com/kangarko/ChatControl-Free/files/3600491/ChatControlZip.zip)

**Comment by kangarko** [comment]
Thanks, that was a problem I just fixed in the next version :)

**Comment by AlwaysAllstar25** [comment]
> Thanks, that was a problem I just fixed in the next version :)

Is the version out now or do you mean it will be released soon? What version is it?

**Comment by kangarko** [comment]
Just the 5.8.6 version
