### ISSUE TITLE
Broadcast message on random time and not timed?

### ISSUE THREAD

**Issue by PachiMc** [kangarko/ChatControl-Free#365]
Hi, the autobroadcast timed option is broken, send messsage between 2m to 5m and multiples times when the delay is of 950 with these options (version 5.8.5)
 Timed:
    Enabled: true
    Random_Order: false
    
    # If random order is enabled, the messages will be put in a cache and not repeat until the cache is empty,
    # then it will be filled again and so on.
    Random_No_Repeat: false
    
    # Prefix and suffix supports variables %player (player name) and %world (world name)
    Prefix: ''
    Suffix: ''
    Delay_Seconds: 950

    # Timed messages per worlds.
    # By default every world includes global messages.
    Message_List:
      
      # Messages displayed in all worlds.
      global:

      - '&7test'

      # In this world will be displayed both global messages and these specified below.
      hardcore:

      
      # In this world will be displayed messages included from hardcore world.
      hardcore_nether:

      
      # No messages will be broadcasted in this world.
      ignored-world:

      
      # Global messages will no be displayed in this world.

**Comment by kangarko** [comment]
Hello,

we are using bukkit API to schedule the message task. If your server is having lags or reduced performance, this delay will not be exact and this may happen. Please ensure your server is running smoothly to eliminate this cause.
