### ISSUE TITLE
Website URL and links not being handled as advertisement

### ISSUE THREAD

**Issue by Leonardo-Fiori** [kangarko/ChatControl-Free#366]
The plugin simply removes the dots and allows the player to send the message containing an URL.. and it does not notify any admin. I edited the rules.txt like this:

`# Domain/URL filter.
`# You can add new domains by inserting '|your_domain' after '|io' (e.g. '|io|pl' for also blocking '.pl' `domains)
`match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?`(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|me|io|tk|ga|it|de)\b
`# If you want to whitelist your server, it is only necessary to add it once in format:
`# website.domain (example: procraft.com)
`# To add more domains simply add them after the last one and divide by |
`ignore string minecraft:|peacefulvanilla.club
`id 2
`before replace dot|\[|\]|\{|\}|\(|\) with .
`before strip [\(\[\]\)]
`then rewrite I am stoopid.
`then deny
`then notify group.moderator &8[&7%ruleID&8] &7%player: &f%message
`handle as advertisement`

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/chatcontrol-pro/wiki/Frequently-Asked-Questions#ad-filter-doesnt-work-all-dots-are-removed-example-wwwgooglecom-becomes-www-google-com
