### ISSUE TITLE
Use displayname in ClearChat and MuteChat broadcast?

### ISSUE THREAD

**Issue by Wolfling1** [kangarko/ChatControl-Free#367]
I'd like to use displayname (prefix and then essentials nick) in MuteChat and ClearChat.

Is this possible? If so, how?

(Sorry if this is not the right place to ask this, i have never used github before.

**Comment by kangarko** [comment]
This is ChatControl not MuteChat and ClearChat plugins. If you're referring to our mute/clear chat feature, you can use the %nick variable in those messages or install PlaceholderAPI to unlock a whole new range or variables (then use %% both at the front and at the end of the variable for PlaceholderAPI.)
