### ISSUE TITLE
%player_name% instead of player's name

### ISSUE THREAD

**Issue by Vinderguy** [kangarko/ChatControl-Free#370]
Fresh installed DeluxeChat 1.14.5 (latest version) displays %player_name% instead of player's name in chat messages, ignoring prefixes, suffixes, format, etc.

Running Paper 1.14.4 with LuckPerms installed.

![Base Profile Screenshot 2019 10 14 - 15 59 11 80](https://user-images.githubusercontent.com/26736457/66757097-a9587900-ee9b-11e9-80bf-6e4c9a884527.png)

**Comment by kangarko** [comment]
This GitHub is for ChatControl. Those two plugins don't play well, you can only use one for formatting your chat.
