### ISSUE TITLE
Commands problems

### ISSUE THREAD

**Issue by erDUKE21** [kangarko/ChatControl-Free#372]
After i upload this plugin on my server, players start complaining about using commands from essentials like: 

/tpa
/back
/warp
/msg

And from other plugins like LoginSecurity: /login

Why that happens?

**Comment by kangarko** [comment]
What is it they are complaining about?

If ChatControl is blocking these commands for having advertisements or swears, you can exclude them in your handlers.yml file.

**Comment by erDUKE21** [comment]
I upload the plugin but strange things happens on the server.

When a players receives a /tpa solicitude and enter /tpaccept it doesn't work anymore.

The same happens with /back and /home commands, they said it doesn't work. Sometimes works and other times don't.

I have LoginSecurity plugin, we needed to use /login to join to the server, for example /login 12345. After this plugin now for some reason we need to join like this /login 12345 12345. Now we need to put 2 times the password.

**Comment by erDUKE21** [comment]
I removed the plugin to confirm the problem with ChatControl and the problem was solved. But i really want this plugin on the server.

**Comment by erDUKE21** [comment]
This plugin works with essentials?

**Comment by kangarko** [comment]
What exactly happens when it 'does not work'? What is the message you're getting when you type /tpa or /login 12345 and it doesn't work?

**Comment by erDUKE21** [comment]
Those commands works sometimes, the console don't show me any issue. 

The problem is, with this plugin all the essentials command works sometimes, if you use /tpa maybe it works or maybe not. Without chat control the essentialsx commands works perfectly. The same happens with the plugin LoginSecurity, before ChatControl we need to type the password 1 time, with ChatControl we need to type 2 time the password. 

With ChatControl for some reason those commands have the possibility to not work.

**Comment by kangarko** [comment]
What happens in the case where it does not work? Can you record me the screen when it does not work? Thanks.

**Comment by erDUKE21** [comment]
Let me check again

**Comment by kangarko** [comment]
@erDUKE21 any update on this?

**Comment by erDUKE21** [comment]
@kangarko Yes, definitely i have the problem on the /login once i install ChatControl. Now all the players need to enter the password two times, some commands doesn't work anymore.

Definitely people start complaining about the using of some commands

I need to remove ChatControl, but i really want this plugin.

Is hard for me to explain exactly, you need to join to the server if you want to see.

**Comment by kangarko** [comment]
Have you tried removing all other plugins except the one for passwords to see if the problem persists?

**Comment by erDUKE21** [comment]
The problem is only with essentialsx and login security, those plugins are very important in the server

**Comment by kangarko** [comment]
I am sorry but it appears to be a problem with compatibility with your plugin setup, you are the only one reporting this, you can try sending me your ChatControl folder as a ZIP so I can take a look

**Comment by erDUKE21** [comment]
Well i disabled the delay to send commands, and it works, now people don't have any problem man

**Comment by kangarko** [comment]
Awesome!
