### ISSUE TITLE
ChatControl is disabled

### ISSUE THREAD

**Issue by 0wM** [kangarko/ChatControl-Free#375]
Everytime i start my server i am getting 
- Error loading ChatControl, plugin is disabled!

Here is log: https://pastebin.com/hQLkRePG
And settings: https://pastebin.com/XxPVS4aK

**Comment by 0wM** [comment]
and i am using PaperMC

**Comment by 0wM** [comment]
I tried to use spigot, but its same

**Comment by JavaFactoryDev** [comment]
Hey OwM, 

It says that your Settings.yml is formatted incorrectly. Please try to reformat it with an Yaml-Validator: http://www.yamllint.com

**Comment by kangarko** [comment]
Your error says that it expected double at Chat.Formatter.Range in settings.yml. Please write 1.0 or 2.0 or  similar there, not 1 or 2 (this is called integer not double).
