### ISSUE TITLE
Chat Staff not working at all

### ISSUE THREAD

**Issue by Emivg** [kangarko/ChatControl-Free#377]
Hello

I have the feature "Staff Chat" enabled in my server with the @ at the start

The problem is, it works for my helpers, when they do @message it shows in the staff chat. Im admin with '*' permission and OP, when I do @message it goes to the normal chat

Im using last version for paper spigot 1.13.2

Regards!

**Comment by kangarko** [comment]
Staff chat is not contained in ChatControl free, please use the other issue channel for the Pro version
