### ISSUE TITLE
1.15 Not hooking into vault for some features

### ISSUE THREAD

**Issue by james090500** [kangarko/ChatControl-Free#378]
The join/kick/leave messages are not hooking into vault to change the prefixes.

`  
Join: §6§l»&r§6 %player has joined the server!`
`Quit: §6§l«&r§6 %player has left the server!`
`Kick: §6§l«&r§6 %player has been forcibly removed!
`

http://i.imgur.com/1E5BDFz.png

`[16:09:06 INFO]: -----------------------------------------------------|`
`[16:09:06 INFO]: ChatControl // Running v5.8.7`
`[16:09:06 INFO]: ChatControl // By kangarko © 2013 - 2019`
`[16:09:14 INFO]: This server is running Paper version git-Paper-27 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)`
`[16:09:14 INFO]: Checking version, please wait...`
`[16:09:14 INFO]: Previous version: git-Paper-26 (MC: 1.15.1)`
`[16:09:14 INFO]: You are running the latest version`

**Comment by james090500** [comment]
https://www.spigotmc.org/resources/chatcontrol%E2%84%A2-the-ultimate-chat-plugin-500-000-downloads-1-2-5-1-14-4.271/updates

Turns out I can't read update logs.

**Comment by kangarko** [comment]
1.15 support is now out!

If you have a problem reading these, ensure your account is the buyer of that plugin. If you continue to have issues contact us via SpigotMC.
