### ISSUE TITLE
Per colour permission - Suggestions

### ISSUE THREAD

**Issue by Geeeeri** [kangarko/ChatControl-Free#379]
Hey!
Would it be possible to add permission to ever colour? This would be rather useful. Right now, I can add permission to my donators to have every single colour, including unreadable ones such as black, or none. 

In my opinion there should be a permission such as `chatcontrol.chat.format.color.red`, with this they could only use the red one. Of course, this would go to every single other one as well. `chatcontrol.chat.format.color.<colorname>`

Hope you consider my suggestion.

**Comment by kangarko** [comment]
Hi, ChatControl free is not receiving new features, use the Pro version where this is already implemented.
