### ISSUE TITLE
Minecraft 1.16.5 PlayerRanks

### ISSUE THREAD

**Issue by duckiesek** [kangarko/ChatControl-Free#38]
Ahoj, chtěl jsem se zeptat, zdali by jsi nějak nepropojil tento plugin s PlayerRanks, protože mají jak tab, tak i chat prefixy, a hodilo by se, aby se dali nastavit velké písmena, tečky, čárky, otazníky a vykřičníky.

**Comment by kangarko** [comment]
Zdravím,

ChatControl podporuje dost veľa funkcií ktoré sa prelínajú s daným pluginom, vyber si buď náš plugin alebo onen, obidva budú spôsobovať konflikty. Neplánujeme žiadnu špeciálnu integráciu.
