### ISSUE TITLE
ChatControl now disabled

### ISSUE THREAD

**Issue by Phamous1** [kangarko/ChatControl-Free#381]
It is giving me a Java error on start up, but i checked and am running current versions.  
[error (2).log](https://github.com/kangarko/ChatControl-Free/files/4103612/error.2.log)
[settings.txt](https://github.com/kangarko/ChatControl-Free/files/4103615/settings.txt)

**Comment by kangarko** [comment]
This channel is for chatcontrol free use the other one for the pro version
