### ISSUE TITLE
Version 1.15.2

### ISSUE THREAD

**Issue by kuba150** [kangarko/ChatControl-Free#382]
When you plan to upgrade free version od your plugin to Minecraft version 1.15.2

**Comment by kangarko** [comment]
It does not work?

**Comment by kuba150** [comment]
Unfortunately yes, please do something with this because I need this
awesome plugin to my server work properly

śr., 5.02.2020, 09:55 użytkownik Matej Pacan <notifications@github.com>
napisał:

**Comment by diannetea** [comment]
I can't get it to work either, using venturechat for formatting

**Comment by kuba150** [comment]
Please try to do something

czw., 6.02.2020, 16:13 użytkownik diannetea <notifications@github.com>
napisał:

**Comment by kangarko** [comment]
How exactly it does not work?

**Comment by diannetea** [comment]
I've done some more testing and it looks like it actually does work for everything except formatting chat.  It blocks commands correctly, but it does not rewrite or replace anything said.

**Comment by diannetea** [comment]
NEVERMIND IM STUPID AND HAD A BYPASS ON MYSELF

**Comment by kuba150** [comment]
What xD

pt., 7.02.2020, 02:23 użytkownik diannetea <notifications@github.com>
napisał:

**Comment by kuba150** [comment]
This is my wrong that ChatControl not working on my server or yours?

pt., 7.02.2020, 23:17 użytkownik Jakub M <kuba.29000@gmail.com> napisał:

**Comment by kangarko** [comment]
Closing, if there is a **specific** problem preventing ChatControl to work, open a new tickets with **exact** steps to reproduce the problem and if you have an error please upload it over to pastebin.com and send it there as well.
