### ISSUE TITLE
Message broadcaster doesn't support multiple lines

### ISSUE THREAD

**Issue by ItsGJK** [kangarko/ChatControl-Free#387]
Creating new lines for the message broadcasting part (either using a new line, or putting \n) doesn't actually create new lines and instead prints everything to the chat in one line:

![image](https://user-images.githubusercontent.com/19877649/77357270-dac05500-6d15-11ea-8f8c-7b2f3e4fcb26.png)

**Comment by kangarko** [comment]
Sorry for the delay! Please comment below if you still have issues.
