### ISSUE TITLE
/help is getting blocked

### ISSUE THREAD

**Issue by JpCuber** [kangarko/ChatControl-Free#389]
Hey there. I'm having difficulty with the plugin causing players to just see 'Unknown Command' when they do /help. I don't want the plugin to block /help from players as I have it changed to be custom using MyCommand. Any way I can disable it from blocking /help?
Thanks!

**Comment by kangarko** [comment]
Can you remove ChatControl to confirm we are causing this problem?

**Comment by kangarko** [comment]
Also take a look at rules/commands.txt and commands.yml to look for aliases and the problem

**Comment by JpCuber** [comment]
My apologies, it just so happened that in updating another plugin, it retired its old config format so it created a new one without me knowing and reset the config (and that plugin blocked /help). It was bad timing as that was right around when I added in chat control. Sorry about that it was another plugin.
