### ISSUE TITLE
chat formatt

### ISSUE THREAD

**Issue by JoaccoG99** [kangarko/ChatControl-Free#392]
I gave every users group the appropiate permission for formatting code but still "default" players are available to do "&1-9, &a-f, &l, &m, &o, &n and &k". I tryied to solve this by denying this permissions:
chatcontrol.chat.format.color
chatcontrol.chat.format.magic
chatcontrol.chat.format.bold
etc...
but nothing changed. Help please, i'm using LuckPerms.

**Comment by AfkF24** [comment]
Can confirm. I'm not even using ChatControl as my chat formatter...

**Comment by kangarko** [comment]
@lackoSK

**Comment by lackoSK** [comment]
Hi guys,

Can you please provide me your ChatControl folder?

Thanks

**Comment by JoaccoG99** [comment]
Here you are ^^
Hope you can solve this

https://www.mediafire.com/file/8dv66en7agzp4vf/ChatControl.rar/file

**Comment by JoaccoG99** [comment]
@lackoSK

**Comment by lackoSK** [comment]
Hello,

Sorry, I am missing it. 
![image](https://user-images.githubusercontent.com/53174757/82154323-513c8780-986d-11ea-815f-16341e3f9ae0.png)

It works flawlessly for me with your configs. Try to use the latest ChatControl from the spigot and updating your server jar.

Sincerely,
Ladislav from MineAcademy.org
