### ISSUE TITLE
Sound notify + Custom message Join/Quit

### ISSUE THREAD

**Issue by dylanjcq** [kangarko/ChatControl-Free#398]
**Hello,**

**I have two small problems that I cannot solve. The first, I would like that when we mention someone in the chat with "@" in front of his name that it makes the noise. Only I do not find how to make it functional in the general chat and not only in the activated commands.**

> Sound_Notify:
>   Enabled: true
>   
>   Notify_Only_When_Afk: true
> 
>   Notify_Only_If_Prefixed_With: '@'
>   
>   Sound: ENTITY_CHICKEN_EGG, 1F, 1.5F
>   Enabled_In_Commands:
>   - msg
>   - m
>   - tell
>   - t
>   - w
>   - r

**Then my second problem being in my opinion a writing problem, I would like to customize my quit/join message with a luckperms place holder in order to display the grade but when I try to insert a place holders or a color code , it tells me error and deactivates the plugins, how should I write this?**

> Messages:
>   Join: %luckperms_prefix% &f{player} &ea quitté la partie
>   Quit: %luckperms_prefix% &f{player} &ea rejoint la partie
>   Kick: %luckperms_prefix% &f{player} &ea été kick de la partie

**Comment by lackoSK** [comment]
Hello,

> I have two small problems that I cannot solve. The first, I would like that when we mention someone in the chat with "@" in front of his name that it makes the noise. Only I do not find how to make it functional in the general chat and not only in the activated commands.

Not possible. 

> Then my second problem being in my opinion a writing problem, I would like to customize my quit/join message with a luckperms place holder in order to display the grade but when I try to insert a place holders or a color code , it tells me error and deactivates the plugins, how should I write this?

what is the error? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by dylanjcq** [comment]
` [18:36:03]: [WARN] org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token [18:36:03]: [WARN] found character '%' that cannot start any token. (Do not use % for indentation) [18:36:03]: [WARN] in 'string', line 164, column 9: [18:36:03]: [WARN] Join: %luckperms_prefix% &f{player} &e ... [18:36:03]: [WARN] ^ [18:36:03]: [WARN] [18:36:03]: [WARN] at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) [18:36:03]: [WARN] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) [18:36:03]: [WARN] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) [18:36:03]: [WARN] at org.mineacademy.chatcontrol.settings.ConfHelper.createFileAndLoad(ConfHelper.java:113) [18:36:03]: [WARN] at org.mineacademy.chatcontrol.settings.Settings.load(Settings.java:23) [18:36:03]: [WARN] at org.mineacademy.chatcontrol.settings.ConfHelper.loadAll(ConfHelper.java:53) [18:36:03]: [WARN] at org.mineacademy.chatcontrol.ChatControl.onEnable(ChatControl.java:88) [18:36:03]: [WARN] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [18:36:03]: [WARN] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) [18:36:03]: [WARN] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) [18:36:03]: [WARN] at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471) [18:36:03]: [WARN] at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385) [18:36:03]: [WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) [18:36:03]: [WARN] at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) [18:36:03]: [WARN] at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) [18:36:03]: [WARN] at java.base/java.lang.Thread.run(Thread.java:834) [18:36:03]: [WARN] Caused by: while scanning for the next token [18:36:03]: [WARN] found character '%' that cannot start any token. (Do not use % for indentation) [18:36:03]: [WARN] in 'string', line 164, column 9: [18:36:03]: [WARN] Join: %luckperms_prefix% &f{player} &e ... [18:36:03]: [WARN] ^ [18:36:03]: [WARN] [18:36:03]: [WARN] at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:419) [18:36:03]: [WARN] at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) [18:36:03]: [WARN] at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586) [18:36:03]: [WARN] at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) [18:36:03]: [WARN] at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:124) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) [18:36:03]: [WARN] at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) [18:36:03]: [WARN] at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) [18:36:03]: [WARN] at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) [18:36:03]: [WARN] at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) [18:36:03]: [WARN] at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) [18:36:03]: [WARN] ... 15 more [18:36:03]: [INFO] !----------------------------------------------! [18:36:03]: [INFO] Error loading ChatControl, plugin is disabled! `

**Comment by lackoSK** [comment]
Hello,

You are missing " " 

Sincerely,
Ladislav from MineAcademy.org

**Comment by dylanjcq** [comment]
It works. Thanks a lot for your help ;)

**Comment by lackoSK** [comment]
👍
