### ISSUE TITLE
Tab complete

### ISSUE THREAD

**Issue by Alv5ro** [kangarko/ChatControl-Free#399]
I've turned disable tab complete off, when i /msg m(tab)/l(tab) it shows 
![image](https://user-images.githubusercontent.com/57922931/82545289-6572d400-9b4e-11ea-88f3-70997b71b465.png)
 It works when I /msg (tab)(some people), but not every person. /warp (tab) works perfectly fine as well.
This is my tab complete part of the config...https://pastebin.com/L65qN79w
I have other plugins, which could interfere with it but I would still need. I have deluxechat, essentialsx and pl-hide pro along with others, but they aren't chat based plugins so I woudn't think they'd interfere.

**Comment by kangarko** [comment]
@lackoSK

**Comment by lackoSK** [comment]
Hello,

Do you have ProtocolLib installed? It's easier to disable it inside spigot.yml set tab-complete to 
-1 to disable it

![image](https://user-images.githubusercontent.com/53174757/82784465-da048600-9e60-11ea-8ba5-36ad74100088.png)

Sincerely,
Ladislav from MineAcademy.org

**Comment by Alv5ro** [comment]
Thank you, that was literally all I had to do XD. Sorry about that, I have a few chat plugins and got really confused!
