### ISSUE TITLE
1.16 - Automatic placeholder updating

### ISSUE THREAD

**Issue by yannic-md** [kangarko/ChatControl-Free#4]
Hi. Is it possible to auto-update the chat placeholders in a certain time? Because it shows the island level (bentobox) from a user in the chat, but if they get a higher island level, the placeholder doesn't update till a restart

**Comment by kangarko** [comment]
Hi, what placeholder is that please? What island plugin do you use?

**Comment by yannic-md** [comment]
Bentobox, AcidIsland, Level-Addon

Level_acidisland_island_level

**Comment by kangarko** [comment]
Got it, what you can try is using variables/ folder and create a new variable with some test name like "island_level" that will produce the Value of "{level_acidisland_island_level}" then use {island_level} in game to see if it still happens

**Comment by R4zzerYT** [comment]
Can you give me a example? i can't understand that configuration..

**Comment by yannic-md** [comment]
still doesnt update, i think its stopping from updating if many users at the same time uses the command and than nothing happens anymore until i restart

**Comment by yannic-md** [comment]
so i mean the command /is level (this takes a while because it uses math for every user)

**Comment by kangarko** [comment]
Thanks, I'd have to have a closer look, please enable me 1-2 more days.

**Comment by kangarko** [comment]
Sorry I totally missed that this is for the free version of ChatControl. Unfortunately there the system is totally different than Pro. If you are running Pro, please let me know, otherwise we are not doing any major updates expect security fixes to the Free edition since 2015.

**Comment by yannic-md** [comment]
My friend has the pro version, but I'm his server admin I thought I can report that here

**Comment by kangarko** [comment]
Great, however we only provide support to buyers. Please PM me from a buyer's account to 'kangarko' at SpigotMC.

**Comment by yannic-md** [comment]
I'll let him know
