### ISSUE TITLE
ad filter doesnt work

### ISSUE THREAD

**Issue by GeorgyGasai** [kangarko/ChatControl-Free#400]
ad filter doesnt work. why? my txt files is default.
my handlers.yml:
advertisement:
  Bypass_With_Permission: "chatcontrol.bypass.ad"
  Ignored_In_Commands:
    - /register
    - /reg
    - /login
    - /l
  
  Player_Warn_Message: "&сВаше сообщение содержит ссылку или IP адрес."
  #Broadcast_Message: "&c{player} might have advertised, alert admins!"
  Console_Message: "{player} violated rule ID {ruleID}, triggered {handler} filter with: {message}"
  
  Staff_Alert_Message: "&8[&7Ad/ID {ruleID}&8] &7{player}: &f{message}"
  Staff_Alert_Permission: chatcontrol.notify.ad
  
  Block_Message: true
  Write_To_File: logs/advertisements.txt

**Comment by kangarko** [comment]
@GeorgyGasai I am very sorry you did not get help here, we have migrated to https://support.mineacademy.org, please open a new ticket there [just mention you are using the free version please]
