### ISSUE TITLE
1.16.5: Error

### ISSUE THREAD

**Issue by RadwolfYT** [kangarko/ChatControl-Free#45]
When I Try to do /chatcontrol reload
I get an error That I don't know how to fix?
![Desktop Screenshot 2021 05 26 - 20 55 29 16 (2)](https://user-images.githubusercontent.com/84648901/119749274-c7060680-be64-11eb-9c5f-ad6dc38041e5.png)

**Comment by kangarko** [comment]
Use https://yaml-online-parser.appspot.com/ to parse your file, it has syntax error.

Put " instead of ' around the "You can join our discord..." messages if it has ' already inside.
