### ISSUE TITLE
1.16.5:   Rejoin_Delay_Seconds: 100

### ISSUE THREAD

**Issue by StoneMcYT** [kangarko/ChatControl-Free#49]
I have a 1.16.5 PaperMc server and I cant seem to get Rejoin delay working.

Anti_Bot:

  Rejoin_Delay_Seconds: 100
  

  Block_Actions_Until_Moved:

    Chat: true

**Comment by kangarko** [comment]
Sorry we're no longer offering updates for this feature in ChatControl Free.
