### ISSUE TITLE
1.16.5: "Could not pass event PlayerKickEvent" issue

### ISSUE THREAD

**Issue by Feniksovich** [kangarko/ChatControl-Free#50]
**Server Core:** git-Purpur-1126 (MC: 1.16.5)
**Plugin Version:** 5.9.1
**Installed plugins:** https://feniksovich.is-inside.me/VMqfOcQH.png

When a player kicks from the server, it throws the following ChatControl error:
https://paste.lucko.me/KxpCQDABRj

**Comment by kangarko** [comment]
Thanks, will be patched
