### ISSUE TITLE
1.17: Plugin Broken when updating to 1.17

### ISSUE THREAD

**Issue by not-3than** [kangarko/ChatControl-Free#52]
The plugin and its commands are broken in 1.17. Upon trying to use the commands for the plugin, it says "An internal error occured while attempting to perform this command"

**Comment by kangarko** [comment]
Please post me your startup log uploaded to pastebin.com

**Comment by not-3than** [comment]
I'll get it to you ASAP. I can't merge back over to 1.17 quite yet, but I should be able to later tonight and send the logs your way.

**Comment by not-3than** [comment]
https://pastebin.com/3t2SmCq9

So sorry for the delay. I had a million things going on. Finally got around to it.
Something to do with ProtocolLib?

**Comment by kangarko** [comment]
That'll be fixed by updating your ProtocolLib
