### ISSUE TITLE
Running Purpur 1.16.5-R0.1-SNAPSHOT and Java 11.0.10: Unhandled exception listening to AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by RageNation-Network** [kangarko/ChatControl-Free#53]
When I am using Admin Chat and sent a message then it is also sent in default chat with admin chat.

Error.log - https://pastebin.com/bjecfpeS

**Comment by kangarko** [comment]
1. Wrong issues channel
2. Read the error message and complete the steps: "Please configure your 'server-name' in server.properties according to mineacademy.org/server-properties first before using BungeeCord features"
