### ISSUE TITLE
Paper 1.17.1: ChatControl will not start

### ISSUE THREAD

**Issue by jmelgar1** [kangarko/ChatControl-Free#54]
31.07 20:31:22 [Server] INFO Enabling ChatControl v5.9.1
31.07 20:31:22 [Server] INFO Hooked into: Essentials
31.07 20:31:22 [Server] WARN java.lang.ClassCastException: class com.earth2me.essentials.Essentials cannot be cast to class com.earth2me.essentials.Essentials (com.earth2me.essentials.Essentials is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @5d1af29e; com.earth2me.essentials.Essentials is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2738648a)
31.07 20:31:22 [Server] WARN at org.mineacademy.chatcontrol.hook.EssentialsHook.<init>(HookManager.java:231)
31.07 20:31:22 [Server] WARN at org.mineacademy.chatcontrol.hook.HookManager.loadDependencies(HookManager.java:64)
31.07 20:31:22 [Server] WARN at org.mineacademy.chatcontrol.ChatControl.onEnable(ChatControl.java:87)
31.07 20:31:22 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
31.07 20:31:22 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
31.07 20:31:22 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
31.07 20:31:22 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304)
31.07 20:31:22 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262)
31.07 20:31:22 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:391)
31.07 20:31:22 [Server] WARN at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
31.07 20:31:22 [Server] WARN at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
31.07 20:31:22 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
31.07 20:31:22 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
31.07 20:31:22 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
31.07 20:31:22 [Server] WARN at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
31.07 20:31:22 [Server] WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
31.07 20:31:22 [Server] WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
31.07 20:31:22 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
31.07 20:31:22 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
31.07 20:31:22 [Server] WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
31.07 20:31:22 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
31.07 20:31:22 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
31.07 20:31:22 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
31.07 20:31:22 [Server] WARN at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
31.07 20:31:22 [Server] WARN at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
31.07 20:31:22 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
31.07 20:31:22 [Server] WARN at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
31.07 20:31:22 [Server] WARN at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
31.07 20:31:22 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
31.07 20:31:22 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
31.07 20:31:22 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
31.07 20:31:22 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
31.07 20:31:22 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
31.07 20:31:22 [Server] INFO !----------------------------------------------!
31.07 20:31:22 [Server] INFO Error loading ChatControl, plugin is disabled!
31.07 20:31:22 [Server] INFO Running on 1.17.1-R0.1-SNAPSHOT (v1_17_R1) and Java 16.0.1
31.07 20:31:22 [Server] INFO !----------------------------------------------!
31.07 20:31:22 [Server] INFO Error: class com.earth2me.essentials.Essentials cannot be cast to class com.earth2me.essentials.Essentials (com.earth2me.essentials.Essentials is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @5d1af29e; com.earth2me.essentials.Essentials is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2738648a)

**Comment by kangarko** [comment]
Use https://github.com/kangarko/ChatControl-Free/releases/tag/5.9.2 and update to the latest EssentialsX
