### ISSUE TITLE
Problem about locale

### ISSUE THREAD

**Issue by HRNGUYEN111** [kangarko/ChatControl-Free#55]
I created a file in plugins/ChatControl/localization/messages_vi.yml. It's not working though I reloaded it!
![image](https://user-images.githubusercontent.com/88438745/128672611-0605868a-853d-47c2-a046-f5abe8106dce.png)
-----------------------------------
![image](https://user-images.githubusercontent.com/88438745/128673064-98d307e2-c446-42d3-aec4-f09cbc38da1e.png)

**Comment by kangarko** [comment]
There is no such locale as messages_vi, you have to create messages_en.yml file and have your Locale key on "en".
