### ISSUE TITLE
Paper 1.17.1: Word being detected as a 'swear'

### ISSUE THREAD

**Issue by RocketManKian** [kangarko/ChatControl-Free#56]
Hey there! So for some reason when player's type 'alt' on my Server they are flagged for it being a swear word, when it clearly isn't. I've looked through the rules.txt file but can't see anything saying 'alt' so I am rather confused...

Here is the full log:
https://gyazo.com/ae9a743b3d9

Thanks!

**Comment by kangarko** [comment]
"alt" is not blocked by the default filter, you can reset your rules/ folder by removing it back to defaults to verify this. Also I am unable to click your gyazo link since it appears to be broken.
