### ISSUE TITLE
Global chat not working without OP

### ISSUE THREAD

**Issue by lynrayy** [kangarko/ChatControl-Free#60]
To report a problem or a bug with this plugin, please follow the three steps below:

1) 1.17.1, 1.18

2) With OP "!" preffix works, but not without op

Plugin version 5.9.1

**Comment by lynrayy** [comment]
chatcontrol.chat.globalrange
Not doing anything

**Comment by kangarko** [comment]
Check your permissions plugin, I was not able to reproduce on LuckPerms.
