### ISSUE TITLE
1.18: Error while startup

### ISSUE THREAD

**Issue by Zoro-6191** [kangarko/ChatControl-Free#61]
![image](https://user-images.githubusercontent.com/52291201/144680787-19dd8890-5401-446b-9fa3-3ccb9067dfe5.png)

I deleted the whole config folder too to allow it to correct itself, but same error. I removed .jar and no more error. Also, I haven't touched config in months but error started coming just a while ago.

**Comment by kangarko** [comment]
Cannot reproduce: ![a](https://i.imgur.com/i1idign.png)

Check that you are on the latest version from Releases folder.
 
Probably your system's encoding is wrong or the files got mis-formatted somehow, I advise going through all files and replacing the invisible tab character with two spaces, you can use Notepad++ for that (replace \t with "  ").
