### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by luckysetor** [kangarko/ChatControl-Free#62]
![ed6fe688](https://user-images.githubusercontent.com/84277820/147572405-666ca756-7924-47c2-8789-beb0c1aa4e15.png)
[archive-2021-12-28T134247Z.tar.gz](https://github.com/kangarko/ChatControl-Free/files/7784939/archive-2021-12-28T134247Z.tar.gz)
I Have An Error On Chat Control Im Installed All Api In PlaceholderApi

**Comment by kangarko** [comment]
Use {luckperms_prefix} instead of %%
