### ISSUE TITLE
Players can bypass chat filter using color codes

### ISSUE THREAD

**Issue by playsenge** [kangarko/ChatControl-Free#63]
If we say we have a chat filter rule using regex in the "rules" folder for "fuck" to be a banned word, you obviously can't type it. But if we allow the player to use color codes in chat, they can bypass it with those.
A simple solution to that would be to ChatColor.stripColors() the message before the check if the message contains banned regex.

![image](https://user-images.githubusercontent.com/40773107/147959034-65805a11-a86e-49a5-ad52-29376d693354.png)

**Comment by kangarko** [comment]
Thanks. We already offer this feature in Pro and Red, not doing feature updates to Free anymore :(

**Comment by playsenge** [comment]
Oh. Well I guess it's open-source? So...

**Comment by kangarko** [comment]
No sorry.

**Comment by playsenge** [comment]
I meant.... I will add it in my version.
