### ISSUE TITLE
1.18: Caps lock warning is on everything

### ISSUE THREAD

**Issue by SnowS0ng** [kangarko/ChatControl-Free#68]
Hello! i am currently in the middle of trying to set up a test server for my friends and I am coming across this issue where the caps lock is triggering even though I set it to false. I even tried giving the permission "chatcontrol.bypass.caps" to general using luck perms and added myself into the general category

I have checked console and there are no errors that is being listed whatsoever

**Comment by kangarko** [comment]
Please follow the issue submitting requirements and reopen. Read them, in your case you also need to send us your permissions list just to be sure and that we can test it. I was not able to reproduce this using LuckPerms.
