### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by legendofgow** [kangarko/ChatControl-Free#69]
How i can add Discord domain to rules.txt.? 

Domain/URL filter.
 You can add new domains by inserting '|your_domain' after '|io' (e.g. '|io|pl' for also blocking '.pl' domains)
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|me|io)\b
If you want to whitelist your server, it is only necessary to add it once in format:
furiapolska.pl (example: Furiapolska.pl)
To add more domains simply add them after the last one and divide by |
ignore string minecraft:|youtube.com|imgur.com|
id 2
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]
handle as advertisement

like this link https://discord.gg/jSnPafC4Tk
this is my invite so i want people to use it in chat :)

**Comment by kangarko** [comment]
Use `ignore string minecraft:|youtube.com|imgur.com|discord.gg`
