### ISSUE TITLE
1.8.9: Compatibility with EazyNick Placeholders

### ISSUE THREAD

**Issue by dearminder** [kangarko/ChatControl-Free#7]
So, The placeholders like %eazynick_chat_prefix% don't seem to works only in ChatControl, it's probably not EazyNick fault because command /papi parse myname %eazynick_chat_prefix% drop a correct formatted text, same with TAB plugin and /tab parse %eazynick_chat_prefix%

**Comment by kangarko** [comment]
Have you tried {eazynick_chat_prefix}?

**Comment by kangarko** [comment]
Unfortunately we cannot guarantee 100% coverage for the 1000s of placeholders PAPI has. If it still won't work I am afraid it's a wontfix kind of a issue at least for now.
