### ISSUE TITLE
1.18.2: Delete dot at every link

### ISSUE THREAD

**Issue by legendofgow** [kangarko/ChatControl-Free#70]
Hello,

How i can delete option that on every link chatcontrol give "." ?

like https://discord.gg/jSnPafC4Tk.

by the dot at the end of the line, links do not work
i have set this to false:

  Grammar:
    Punctualize every sentence. Ignores URLs.
    Insert_Dot:
      Enabled: false
      Min_Message_Length: 5

But still is dot at end of link ;/

**Comment by kangarko** [comment]
Sorry, this cannot be disabled unfortunately, if it's caused by the Insert_Dot filter. I apology I was not able to help.
