### ISSUE TITLE
1.18.2: How to stop spaces happening when they dont have a suffix

### ISSUE THREAD

**Issue by LGLLewis** [kangarko/ChatControl-Free#71]
This is my chat format     Message_Format: '%luckperms_prefix% %deluxetags_tag% %essentials_nickname% &7»&r {message}'

However when they dont have a deluxtag there is an extra space inbetween the prefix and the name and i dont know how to stop that

**Comment by kangarko** [comment]
Try using the following syntax: {luckperms_prefix} and make sure you have PlaceholderAPI installed with the right expansion pack
