### ISSUE TITLE
Minecraft NachoSpigot 1.8.8: How to make a chat filter

### ISSUE THREAD

**Issue by itzdrli** [kangarko/ChatControl-Free#72]
How can i make i chat filter?
for example when someone sent `@aaaa` and others will only see the `aaaa` and they won't see the `@`

**Comment by kangarko** [comment]
See rules/chat.txt file, such as

match \@
then replace

**Comment by itzdrli** [comment]
> See rules/chat.txt file, such as
> 
> match @ then replace

hey, the replace is working but isn't same as im thinking about,
im using chatcontrol for a bedwars plugin's chat format, and the reason of i wanna block the '@' is when player type @and message,then it will be shout to global, but when i replace the @ to nothing,i can't even shout to global, im not sure to ask this question to you or to the author of that bedwars plugin.

**Comment by kangarko** [comment]
I don't think ChatControl is a right usage for a hacky workaround like that, you should use the official way from bedwars or look into commands.yml file in your root server's folder to create a shortcut such as /global
