### ISSUE TITLE
IMPORTANT: Need to update PlaceholdersAPI dependecy to latest

### ISSUE THREAD

**Issue by PinoOG** [kangarko/ChatControl-Free#75]
PlaceholdersAPI has released a new update, and something has changed on their API. I have tested CC-Free with PlaceholdersAPI 2.11.2 and the plugin doesn't work as with PlaceholdersAPI 2.11.1(which is the dependecy in pom.xml) in fact there are a lot of errors, not in console but in game, like not recognising some words, or not applying some rules.

**Comment by kangarko** [comment]
Thanks, updated!

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Free/releases/tag/5.9.5

**Comment by PinoOG** [comment]
Thank you for this great resource! By the way, I am one of your students
