### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by zBvczx** [kangarko/ChatControl-Free#79]
i use 1.19.4 paper . ( java 20 ) 

the problem : packets file in the rules folder doesnt work . 

1 : i use protectol lib . 

2 : the plugin was working perfectly in 1.16.5 ( java 8 )

**Comment by kangarko** [comment]
As said in settings.yml, packet rules won't work on Minecraft 1.19 and up. Upgrade to mineacademy.org/chatcontrol-red for new MC support.

**Comment by kangarko** [comment]
I am a hobby developer managing 5+ plugins, I unfortunately don't have time for everything.
