### ISSUE TITLE
1.16.2: Turning off "Anti Spam" For commands in the config

### ISSUE THREAD

**Issue by EasyMcCheesyMC** [kangarko/ChatControl-Free#8]
Hi! 

On my minecraft server i found this plugin really usefull, but it is one problem.

How do i turn of "Anti Spam" on commands?
Because Anti Spam is not letting the players write a commands two times in a row, so for example they cant take /home two times in a row.

How do i fix this??

- Adrian H.

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#how-do-i-disable-anti-spam--messages-please-waitdo-not-repeat-similar-commandmessage
