### ISSUE TITLE
Minecraft 1.16.5: PlaceholderAPI Does not support PlaceholderExpansions

### ISSUE THREAD

**Issue by dgrachov** [kangarko/ChatControl-Free#80]
I am writing my plugin and hooking placeholderapi. I've registered a placeholderexpansion and the command /papi parse parses my placeholders correctly, however when I use them in Message_Format, they remain unchanged.
![Screenshot_5](https://github.com/kangarko/ChatControl-Free/assets/69466627/03e3abc4-8ac9-4571-bcd9-a1b5adf19c18)
![Screenshot_7](https://github.com/kangarko/ChatControl-Free/assets/69466627/44e70625-3d28-4103-88a4-1b025c479cf8)

**Comment by dgrachov** [comment]
Just tested it on other plugins and all placeholders are working perfectly in every plugin that supports placeholderapi, except ChatControl.

**Comment by kangarko** [comment]
Apologizes for the delay, have you tried using {syntax} instead of %syntax%?

**Comment by kangarko** [comment]
Also try using /chc info variables which works as /papi parse.
