### ISSUE TITLE
Paper 1.20.4: ProtocolLIB and chatcontrol not working together.

### ISSUE THREAD

**Issue by DakotaPlayz** [kangarko/ChatControl-Free#81]
1) ProtocolLIB and chatcontrol-free not loading together and breaking.

2) Current situation is as mention before, ProtocolLIB and ChatControl-Free is not loading properly and disabling when starting server. I have updated to and downgrade to each specific version and it's not working at all, I remove one or the other plugin and they respective plugins load as intended.

3) https://pastebin.com/5syxz54t

**Comment by kangarko** [comment]
Handled via email
