### ISSUE TITLE
Is mineacademy-repo down?

### ISSUE THREAD

**Issue by Elikill58** [kangarko/ChatControl-Free#82]
Hello,

It seems the repository [here](https://bitbucket.org/kangarko/libraries/raw/master) seems down. Can you fix it ?

Also, it seems you're using custom repo for plugin that already share their plugin on a repository, why ?

**Comment by kangarko** [comment]
We've moved this repo since, you can find it in the Foundation source code at my github. Also sorry, but ChatControl Free is no longer supported.
